//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.34011
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Obbligo_o_verita.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Obbligo_o_verita.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a aggiungi giocatori.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a .
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a avanti.
        /// </summary>
        public static string Avanti {
            get {
                return ResourceManager.GetString("Avanti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ritorna al menu.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a vuoi fare un altro giro?.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a database.
        /// </summary>
        public static string Db {
            get {
                return ResourceManager.GetString("Db", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a fatto.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a fine.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a [Il tuo commento va qui]
        ///
        ///
        ///---------------------------------
        ///Device Name: {0}
        ///Device Manufacturer: {1}
        ///Device Firmware Version: {2}
        ///Device Hardware Version: {3}
        ///Application Version: {4}
        ///---------------------------------.
        /// </summary>
        public static string FeedbackBody {
            get {
                return ResourceManager.GetString("FeedbackBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mi dispiace che tu non abbia voluto votare Obbligo o Verità.
        ///
        ///Parlaci della tua esperienza con l&apos;app o suggeriscici come migliorarla!.
        /// </summary>
        public static string FeedbackMessage1 {
            get {
                return ResourceManager.GetString("FeedbackMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No, grazie!.
        /// </summary>
        public static string FeedbackNo {
            get {
                return ResourceManager.GetString("FeedbackNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ToR Feedback.
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Possiamo migliorarla?.
        /// </summary>
        public static string FeedbackTitle {
            get {
                return ResourceManager.GetString("FeedbackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a AresDev@outlook.it.
        /// </summary>
        public static string FeedbackTo {
            get {
                return ResourceManager.GetString("FeedbackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dai Feedback.
        /// </summary>
        public static string FeedbackYes {
            get {
                return ResourceManager.GetString("FeedbackYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ciao, giocatore.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Truth or dare è il classico gioco di gruppo in cui si deve rispondere in modo sincero a varie domande oppure fare qualcosa che faccia divertire i tuoi amici. In questo gioco troverai centinaia di domande ed obblighi.                                Il gioco funziona a gironi, alla fine di ogni prova al giocatore viene assegnato un punteggio a seconda di come ha superato la prova data. Alla fine del girone vince il giocatore che ha il punteggio piu alto..
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a inserisci il tuo nome!.
        /// </summary>
        public static string Inserisci {
            get {
                return ResourceManager.GetString("Inserisci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a aggiungi obbligo o verità.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a prossimo giocatore.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a no.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a nuova partita.
        /// </summary>
        public static string Nuova {
            get {
                return ResourceManager.GetString("Nuova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a obbligo.
        /// </summary>
        public static string Obbligo {
            get {
                return ResourceManager.GetString("Obbligo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a gioca.
        /// </summary>
        public static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a giocatori.
        /// </summary>
        public static string Player {
            get {
                return ResourceManager.GetString("Player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a punteggi.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sarebbe splendido se votassi l&apos;app con 5 stelle.
        ///
        ///Mostrare apprezzamento sullo store ci aiuta a continuare a lavorare sull&apos;app e rendere le cose migliori!.
        /// </summary>
        public static string RatingMessage1 {
            get {
                return ResourceManager.GetString("RatingMessage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sembra che tu stia usando molto Obbligo o Verità!
        ///
        ///Perchè non dare 5 stelle per dirci che ti piace?.
        /// </summary>
        public static string RatingMessage2 {
            get {
                return ResourceManager.GetString("RatingMessage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a No, grazie!.
        /// </summary>
        public static string RatingNo {
            get {
                return ResourceManager.GetString("RatingNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Giocone.
        /// </summary>
        public static string RatingTitle {
            get {
                return ResourceManager.GetString("RatingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dai 5 stelle.
        /// </summary>
        public static string RatingYes {
            get {
                return ResourceManager.GetString("RatingYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a rifiutato.
        /// </summary>
        public static string Refused {
            get {
                return ResourceManager.GetString("Refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a it-IT.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a scegli la modalità!.
        /// </summary>
        public static string Scegli {
            get {
                return ResourceManager.GetString("Scegli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a start page.
        /// </summary>
        public static string StartPageTitle {
            get {
                return ResourceManager.GetString("StartPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attenzione!.
        /// </summary>
        public static string Text1 {
            get {
                return ResourceManager.GetString("Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vuoi davvero terminare la partita?.
        /// </summary>
        public static string Text2 {
            get {
                return ResourceManager.GetString("Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a verita.
        /// </summary>
        public static string Verità {
            get {
                return ResourceManager.GetString("Verità", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a visualizza il database.
        /// </summary>
        public static string Visualize {
            get {
                return ResourceManager.GetString("Visualize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a si.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
